-- Create the books table
CREATE TABLE books (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255),
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    notes TEXT,
    date_read DATE,
    cover_url VARCHAR(255),
    genre VARCHAR(255)
);

-- Insert 50 sample books
INSERT INTO books (title, author, rating, notes, date_read, cover_url, genre) VALUES
('The Great Gatsby', 'F. Scott Fitzgerald', 5, 'A classic novel about the American Dream.', '2023-01-15', 'https://covers.openlibrary.org/b/id/8151273-M.jpg', 'Fiction'),
('To Kill a Mockingbird', 'Harper Lee', 4, 'A powerful story about racial injustice.', '2023-02-10', 'https://covers.openlibrary.org/b/id/8151274-M.jpg', 'Fiction'),
('1984', 'George Orwell', 5, 'A dystopian novel about totalitarianism.', '2023-03-05', 'https://covers.openlibrary.org/b/id/8151275-M.jpg', 'Fiction'),
('Pride and Prejudice', 'Jane Austen', 4, 'A romantic novel about Elizabeth Bennet.', '2023-04-20', 'https://covers.openlibrary.org/b/id/8151276-M.jpg', 'Fiction'),
('The Catcher in the Rye', 'J.D. Salinger', 3, 'A story about teenage rebellion.', '2023-05-12', 'https://covers.openlibrary.org/b/id/8151277-M.jpg', 'Fiction'),
('Moby Dick', 'Herman Melville', 4, 'An epic tale of obsession and revenge.', '2023-06-18', 'https://covers.openlibrary.org/b/id/8151278-M.jpg', 'Fiction'),
('War and Peace', 'Leo Tolstoy', 5, 'A historical novel set during the Napoleonic Wars.', '2023-07-22', 'https://covers.openlibrary.org/b/id/8151279-M.jpg', 'Fiction'),
('The Odyssey', 'Homer', 4, 'An ancient Greek epic poem.', '2023-08-30', 'https://covers.openlibrary.org/b/id/8151280-M.jpg', 'Fiction'),
('Ulysses', 'James Joyce', 3, 'A modernist novel set in Dublin.', '2023-09-14', 'https://covers.openlibrary.org/b/id/8151281-M.jpg', 'Fiction'),
('The Brothers Karamazov', 'Fyodor Dostoevsky', 5, 'A philosophical novel about faith and doubt.', '2023-10-05', 'https://covers.openlibrary.org/b/id/8151282-M.jpg', 'Fiction'),
('Crime and Punishment', 'Fyodor Dostoevsky', 4, 'A psychological thriller about guilt and redemption.', '2023-11-11', 'https://covers.openlibrary.org/b/id/8151283-M.jpg', 'Fiction'),
('The Divine Comedy', 'Dante Alighieri', 5, 'An epic poem about the afterlife.', '2023-12-25', 'https://covers.openlibrary.org/b/id/8151284-M.jpg', 'Fiction'),
('The Iliad', 'Homer', 4, 'An ancient Greek epic poem about the Trojan War.', '2024-01-01', 'https://covers.openlibrary.org/b/id/8151285-M.jpg', 'Fiction'),
('Don Quixote', 'Miguel de Cervantes', 3, 'A satirical novel about chivalry.', '2024-02-14', 'https://covers.openlibrary.org/b/id/8151286-M.jpg', 'Fiction'),
('The Republic', 'Plato', 4, 'A philosophical dialogue about justice.', '2024-03-08', 'https://covers.openlibrary.org/b/id/8151287-M.jpg', 'Non-Fiction'),
('The Aeneid', 'Virgil', 5, 'An epic poem about the founding of Rome.', '2024-04-22', 'https://covers.openlibrary.org/b/id/8151288-M.jpg', 'Fiction'),
('The Canterbury Tales', 'Geoffrey Chaucer', 3, 'A collection of stories told by pilgrims.', '2024-05-30', 'https://covers.openlibrary.org/b/id/8151289-M.jpg', 'Fiction'),
('The Sound and the Fury', 'William Faulkner', 4, 'A modernist novel about the Compson family.', '2024-06-15', 'https://covers.openlibrary.org/b/id/8151290-M.jpg', 'Fiction'),
('Brave New World', 'Aldous Huxley', 5, 'A dystopian novel about a futuristic society.', '2024-07-04', 'https://covers.openlibrary.org/b/id/8151291-M.jpg', 'Fiction'),
('One Hundred Years of Solitude', 'Gabriel Garcia Marquez', 4, 'A magical realism novel about the Buendía family.', '2024-08-19', 'https://covers.openlibrary.org/b/id/8151292-M.jpg', 'Fiction'),
('The Alchemist', 'Paulo Coelho', 4, 'A philosophical book about following your dreams.', '2024-09-01', 'https://covers.openlibrary.org/b/id/8151293-M.jpg', 'Fiction'),
('The Hobbit', 'J.R.R. Tolkien', 5, 'A fantasy novel about Bilbo Baggins.', '2024-10-15', 'https://covers.openlibrary.org/b/id/8151294-M.jpg', 'Fiction'),
('The Lord of the Rings', 'J.R.R. Tolkien', 5, 'An epic fantasy trilogy.', '2024-11-20', 'https://covers.openlibrary.org/b/id/8151295-M.jpg', 'Fiction'),
('Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 5, 'The first book in the Harry Potter series.', '2024-12-25', 'https://covers.openlibrary.org/b/id/8151296-M.jpg', 'Fiction'),
('The Da Vinci Code', 'Dan Brown', 4, 'A thriller about secret societies.', '2025-01-10', 'https://covers.openlibrary.org/b/id/8151297-M.jpg', 'Fiction'),
('The Shining', 'Stephen King', 4, 'A horror novel about a haunted hotel.', '2025-02-14', 'https://covers.openlibrary.org/b/id/8151298-M.jpg', 'Fiction'),
('The Girl with the Dragon Tattoo', 'Stieg Larsson', 4, 'A crime novel about a hacker and a journalist.', '2025-03-08', 'https://covers.openlibrary.org/b/id/8151299-M.jpg', 'Fiction'),
('The Hunger Games', 'Suzanne Collins', 5, 'A dystopian novel about survival.', '2025-04-22', 'https://covers.openlibrary.org/b/id/8151300-M.jpg', 'Fiction'),
('The Road', 'Cormac McCarthy', 4, 'A post-apocalyptic novel about a father and son.', '2025-05-30', 'https://covers.openlibrary.org/b/id/8151301-M.jpg', 'Fiction'),
('The Book Thief', 'Markus Zusak', 5, 'A historical novel set in Nazi Germany.', '2025-06-15', 'https://covers.openlibrary.org/b/id/8151302-M.jpg', 'Fiction'),
('The Kite Runner', 'Khaled Hosseini', 4, 'A story of friendship and redemption.', '2025-07-04', 'https://covers.openlibrary.org/b/id/8151303-M.jpg', 'Fiction'),
('The Fault in Our Stars', 'John Green', 4, 'A young adult novel about love and loss.', '2025-08-19', 'https://covers.openlibrary.org/b/id/8151304-M.jpg', 'Fiction'),
('Gone Girl', 'Gillian Flynn', 4, 'A psychological thriller about a missing wife.', '2025-09-01', 'https://covers.openlibrary.org/b/id/8151305-M.jpg', 'Fiction'),
('The Martian', 'Andy Weir', 5, 'A science fiction novel about survival on Mars.', '2025-10-15', 'https://covers.openlibrary.org/b/id/8151306-M.jpg', 'Fiction'),
('The Night Circus', 'Erin Morgenstern', 4, 'A fantasy novel about a magical circus.', '2025-11-20', 'https://covers.openlibrary.org/b/id/8151307-M.jpg', 'Fiction'),
('The Goldfinch', 'Donna Tartt', 4, 'A novel about art and obsession.', '2025-12-25', 'https://covers.openlibrary.org/b/id/8151308-M.jpg', 'Fiction'),
('The Silent Patient', 'Alex Michaelides', 4, 'A psychological thriller about a mute patient.', '2026-01-10', 'https://covers.openlibrary.org/b/id/8151309-M.jpg', 'Fiction'),
('The Seven Husbands of Evelyn Hugo', 'Taylor Jenkins Reid', 5, 'A novel about a Hollywood star.', '2026-02-14', 'https://covers.openlibrary.org/b/id/8151310-M.jpg', 'Fiction'),
('Where the Crawdads Sing', 'Delia Owens', 4, 'A mystery novel about a girl in the marsh.', '2026-03-08', 'https://covers.openlibrary.org/b/id/8151311-M.jpg', 'Fiction'),
('Educated', 'Tara Westover', 5, 'A memoir about growing up in a strict household.', '2026-04-22', 'https://covers.openlibrary.org/b/id/8151312-M.jpg', 'Non-Fiction'),
('Thinking, Fast and Slow', 'Daniel Kahneman', 5, 'A book about how we think and make decisions.', '2026-05-30', 'https://covers.openlibrary.org/b/id/8151313-M.jpg', 'Non-Fiction'),
('Sapiens: A Brief History of Humankind', 'Yuval Noah Harari', 4, 'A book about the history of humanity.', '2026-06-15', 'https://covers.openlibrary.org/b/id/8151314-M.jpg', 'Non-Fiction'),
('The Power of Habit', 'Charles Duhigg', 4, 'A book about how habits work and how to change them.', '2026-07-04', 'https://covers.openlibrary.org/b/id/8151315-M.jpg', 'Non-Fiction'),
('Atomic Habits', 'James Clear', 5, 'A guide to building good habits and breaking bad ones.', '2026-08-19', 'https://covers.openlibrary.org/b/id/8151316-M.jpg', 'Non-Fiction'),
('The Subtle Art of Not Giving a F*ck', 'Mark Manson', 4, 'A counterintuitive approach to living a good life.', '2026-09-01', 'https://covers.openlibrary.org/b/id/8151317-M.jpg', 'Non-Fiction'),
('How to Win Friends and Influence People', 'Dale Carnegie', 5, 'A classic book on interpersonal skills.', '2026-10-15', 'https://covers.openlibrary.org/b/id/8151318-M.jpg', 'Non-Fiction'),
('The 7 Habits of Highly Effective People', 'Stephen R. Covey', 4, 'A book about personal and professional effectiveness.', '2026-11-20', 'https://covers.openlibrary.org/b/id/8151319-M.jpg', 'Non-Fiction'),
('Deep Work', 'Cal Newport', 5, 'A book about focusing in a distracted world.', '2026-12-25', 'https://covers.openlibrary.org/b/id/8151320-M.jpg', 'Non-Fiction');